PLC_angle: 86.38

PLC_position: 0.0

end_effector:

  color: bwr

  pose_6: [-0.0485, 0.0, 0.091]

  size: [0.147, 0.18, 0.182]

  type: Box

manipulator_type: LR_Mate_200iD_7L

obstacles:

  desktop:

    color: Reds_r

    pose_b: [0.3575, 0.0, -0.04]

    size: [1.0, 1.0, 0.08]

    type: Box

  foundation:

    color: Reds_r

    pose_b: [0.6035, 0.0, 0.12825]

    size: [0.09, 0.15, 0.2565]

    type: Box

  rooftop:

    color: Reds_r

    pose_b: [0.3575, 0.0, 1.15]

    size: [1.0, 1.0, 0.08]

    type: Box

  slide:

    color: Reds_r

    pose_b: [0.0255, -0.42425, 0.09]

    size: [0.06, 0.1025, 0.18]

    type: Box
